### PR TITLE
82 handling non apc names in update taxonomy

### PR DESCRIPTION
**Pull request by wcornwell**
found a reasonably simple way to do this.

### CODE REVIEW

**Comment by fontikar** [comment]
@wcornwell I am getting an error with the following example used in the issue #82 

```
aa <- create_taxonomic_update_lookup(c("Acacia sp.", "Dendropanax amplifolius",
+                    "Acanthopanax divaricatum", "Eucalyptus sp."), resources=resources)
Checking alignments of 4 taxa

  -> 0 names already matched; 0 names checked but without a match; 4 taxa yet to be checked
Error in `bind_rows()` at APCalign/R/create_taxonomic_update_lookup.R:118:4:
! Can't combine `..1$source` <logical> and `..2$source` <character>.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by wcornwell** [comment]
interesting.  will investigate. We should make that specific example into a test because all of our tests were passing

**Comment by wcornwell** [comment]
ahhhh it's the case where update_taxonomy returns nothing

**Comment by fontikar** [comment]
Lets convert the below as a test! :) I don't know what to expect? Both Genus level ID should -> NA right? Unsure of the other two

```
aa <- create_taxonomic_update_lookup(c("Acacia sp.", "Dendropanax amplifolius",
+                    "Acanthopanax divaricatum", "Eucalyptus sp."), resources=resources)
```

**Comment by fontikar** [comment]
Yeah I think we need to handle these at either align_taxa level or update_taxononomy level

**Comment by wcornwell** [comment]
i'm on it

**Comment by wcornwell** [comment]
new behavior: 
Screenshot 2023-08-03 at 2 11 38 pm

**Review by fontikar — APPROVED** [review]
Yay! Merge away

**Pull request merged**
