### PR TITLE
Cran preparation for APCalign 0.0.1 release

### PR DESCRIPTION
**Pull request by fontikar**
Address #84 

- Updated DESCRIPTION
- Added and updated NEWS.md
- cran_comments.md
- Updates to Rbuilldignore

### CODE REVIEW

**Comment by wcornwell** [comment]
do we want to resolve https://github.com/traitecoevo/APCalign/issues/70 as part of this?

**Comment by fontikar** [comment]
> do we want to resolve #70 as part of this?

Can do. 
What do you think you of these roles? [Following these guidelines](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf)
@dfalster auth, cre
@ehwenk auth, ctb
@wcornwell auth, ctb
@fontikar  auth, ctb (though I am not sure how much I can contribute to writing about plant taxonomy so happy to be ctb only) 
Carl B @ctb for contentID? Would he like to be on paper as auth?
Unsure about Herve's role (my guess auth)
Waiting on Anna Monroe and Anne Fuchs (both probably auth, ctb)
Unsure about Fabrice, and Ruby and Sophie

**Comment by dfalster** [comment]
Hi @fontikar , good idea. Regarding the uncertainty

- Carl B as ctb for contentID: yes, for now, we'll invite his for paper and we can update role later as needed
- Herve : not yet,  might contribute to paper and we can add then
- Anna Monroe and Anne Fuchs (both probably auth, ctb):  leave off for now, can add later
- Fabrice: no, he contributed to another package which I used as template for this, but we've swapped that out for contentID
- Ruby and Sophie: only very small commits so don't list yet. Would be good to involve them in paper with use cases and testing, we can add them then if they contribute there .

**Comment by wcornwell** [comment]
> COPYRIGHT HOLDER: Your name here

**Review by wcornwell — APPROVED** [review]
looks good

**Comment by ctb** [comment]
(note I'm @ctb ;)

**Comment by fontikar** [comment]
Oh dear so sorry for the tag! Thanks for dropping by 😅

**Pull request merged**
