### PR TITLE
simplfying data download and adding a trycatch

### PR DESCRIPTION
**Pull request by wcornwell**
Simplifying data download to make server errors less likely, and adding a trycatch for the download step.

### CODE REVIEW

**Review by fontikar — COMMENTED** [review]
Is removing contentid completely a good move? @wcornwell @dfalster? I think this is a good intermediate solution to stay on CRAN until we figure out contentid properly. thoughts?

**Comment by wcornwell** [comment]
until the data is in more than one place, I don't think contentID functionality makes sense?  Once there is APC has a canonical place also, then we can revisit?

**Comment by dfalster** [comment]
I agree with Will!

**Comment by fontikar** [comment]
> until the data is in more than one place, I don't think contentID functionality makes sense? Once APC has a canonical place also, then we can revisit? Do you want to merge some of your changes in @fontikar ?

I will merge `graceful` into `simplifydataloading` instead to `master` then we can merge this branch in. We have made edits on the same files and potentially same lines so I will have to resolve some conflicts so we have a good frankenstein :)

**Comment by fontikar** [comment]
> until the data is in more than one place, I don't think contentID functionality makes sense? Once APC has a canonical place also, then we can revisit? Do you want to merge some of your changes in @fontikar ?

@wcornwell can I change the merging base into `develop`, that way you can merge that in and I can merge my changes in from `graceful` into develop seperately

**Comment by wcornwell** [comment]
@fontikar do whatever makes sense to you!  many options

**Comment by fontikar** [comment]
Wahoo! Go for it @wcornwell make sure you **squash before merging** :D

**Review by fontikar — APPROVED** [review]
Nice and simply changes to keep us on CRAN. Squash and merge away!

**Pull request merged**
