### PR TITLE
fix genus-level alignments

### PR DESCRIPTION
**Pull request by ehwenk**
Solving genus-level alignments described in issue #88 

Have moved to its own branch, so it can be reviewed and merged in immediately.

### CODE REVIEW

**Review by dfalster — APPROVED** [review]
Great! 

I'm surprised the existing code doesn't work, but ok

**Comment by fontikar** [comment]
> I'm surprised the existing code doesn't work, but ok


Yeah me too, just testing now and I might add a test to make sure!

**Comment by fontikar** [comment]
I added a very simple unit test for this bug fix https://github.com/traitecoevo/APCalign/pull/95 
The test needs to get approved and merged into master first, then pulled into this branch to make sure it passes that test then we can merge this PR in @ehwenk

**Review by fontikar — CHANGES_REQUESTED** [review]
Need to pull in unit test on #95 first before merging! Otherwise a great fix :D

**Comment by fontikar** [comment]
OK these should pass :D

**Review by fontikar — APPROVED** [review]

**Comment by fontikar** [comment]
@ehwenk go ahead and squash and merge 🚀

**Pull request merged**
