### PR TITLE
Removing hard limit on current downloads and documentation wording improvements

### PR DESCRIPTION
**Pull request by wcornwell**

### CODE REVIEW

**Comment by fontikar** [comment]
gahhh why is mac failing AGAIN

**Comment by wcornwell** [comment]
`remotes::install_github("apache/arrow/r@f8ef09a2")` works locally, so this was a github change on their mac CI.

**Review by fontikar — COMMENTED** [review]
Stupid mac! Good idea to remove these, could you update the NEWS.md and bump the version number please in the DESCRIPTION

**Review by ehwenk — APPROVED** [review]
This looks good. I agree that the n_max will create ever more problems, as APC keeps getting longer

**Comment by ehwenk** [comment]
One of my branches had all tests passing yesterday, and then this evening, oddly switched to the macos test failing - so it isn't specific to this branch

**Comment by wcornwell** [comment]
yeah it's a new github CI compiler problem.  might get fixed without us doing anything

**Pull request merged**
